//returns an placeholder image in base64 format - for next/image
export default function tarotCards() {
  const cards = {
    en: [
      "fool",
      "magician",
      "high-priestess",
      "empress",
      "empreror",
      "hierophant",
      "lovers",
      "chariot",
      "strength",
      "hermit",
      "wheel-of-fortune",
      "justice",
      "hanged-man",
      "death",
      "temperance",
      "devil",
      "tower",
      "star",
      "moon",
      "sun",
      "judgement",
      "world",
      "ace-of-wands",
      "two-of-wands",
      "three-of-wands",
      "four-of-wands",
      "five-of-wands",
      "six-of-wands",
      "seven-of-wands",
      "eight-of-wands",
      "nine-of-wands",
      "ten-of-wands",
      "princess-of-wands",
      "knight-of-wands",
      "queen-of-wands",
      "king-of-wands",
      "ace-of-cups",
      "two-of-cups",
      "three-of-cups",
      "four-of-cups",
      "five-of-cups",
      "six-of-cups",
      "seven-of-cups",
      "eight-of-cups",
      "nine-of-cups",
      "ten-of-cups",
      "princess-of-cups",
      "knight-of-cups",
      "queen-of-cups",
      "king-of-cups",
      "ace-of-swords",
      "two-of-swords",
      "three-of-swords",
      "four-of-swords",
      "five-of-swords",
      "six-of-swords",
      "seven-of-swords",
      "eight-of-swords",
      "nine-of-swords",
      "ten-of-swords",
      "princess-of-swords",
      "knight-of-swords",
      "queen-of-swords",
      "king-of-swords",
      "ace-of-pentacles",
      "two-of-pentacles",
      "three-of-pentacles",
      "four-of-pentacles",
      "five-of-pentacles",
      "six-of-pentacles",
      "seven-of-pentacles",
      "eight-of-pentacles",
      "nine-of-pentacles",
      "ten-of-pentacles",
      "princess-of-pentacles",
      "knight-of-pentacles",
      "queen-of-pentacles",
      "king-of-pentacles",
    ],
    pl: [
      "głupiec",
      "mag",
      "kapłanka",
      "cesarzowa",
      "cesarz",
      "papież",
      "kochankowie",
      "rydwan",
      "siła",
      "pustelnik",
      "koło fortuny",
      "sprawiedliwość",
      "wisielec",
      "śmierć",
      "powściągliwość",
      "diabeł",
      "wieża",
      "gwiazda",
      "księżyc",
      "słońce",
      "sąd ostateczny",
      "świat",
      "as różdżek",
      "dwie różdżki",
      "trzy różdżki",
      "cztery różdżki",
      "pięć różdżek",
      "sześć różdżek",
      "siedem różdżek",
      "osiem różdżek",
      "dziewięć różdżek",
      "dziesięć różdżek",
      "paź różdżek",
      "rycerz różdżek",
      "królowa różdżek",
      "król różdżek",
      "as pucharów",
      "dwa puchary",
      "trzy puchary",
      "cztery puchary",
      "pięć pucharów",
      "sześć pucharów",
      "siedem pucharów",
      "osiem pucharów",
      "dziewięć pucharów",
      "dziesięć pucharów",
      "paź pucharów",
      "rycerz pucharów",
      "królowa pucharów",
      "król pucharów",
      "as mieczy",
      "dwa miecze",
      "trzy miecze",
      "cztery miecze",
      "pięć mieczy",
      "ześć mieczy",
      "siedem mieczy",
      "osiem mieczy",
      "dziewięć mieczy",
      "dziesięć mieczy",
      "paź mieczy",
      "rycerz mieczy",
      "królowa mieczy",
      "król mieczy",
      "as pentakli",
      "dwa pentakle",
      "trzy pentakle",
      "cztery pentakle",
      "pięć pentakli",
      "sześć pentakli",
      "siedem pentakli",
      "ósemka pentakli",
      "dziewięć pentakli",
      "dziesięć pentakli",
      "paź pentakli",
      "rycerz pentakli",
      "królowa pentakli",
      "król pentakli",
    ],
  };
  return cards;
}
